const imagePaths = [
    'image/[雲少女写真] 写SchoolGirl.II [27P]/1.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/2.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/3.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/4.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/5.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/6.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/7.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/8.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/9.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/10.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/11.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/12.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/13.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/14.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/15.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/16.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/17.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/18.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/19.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/20.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/21.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/22.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/23.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/24.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/25.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/26.jpg',
    'image/[雲少女写真] 写SchoolGirl.II [27P]/27.jpg',
];

const descriptions = [
    '这是一张精美的风景照片，展现了自然的壮丽景色。',
    '人物特写，捕捉了瞬间的情感表达。',
    '静物摄影，展现了物品的质感和细节。',
    '城市风光，展现了现代都市的繁华景象。',
    '自然风光，展现了山川河流的壮丽景色。',
    '人像摄影，展现了人物的自然表情。',
    '静物摄影，展现了物品的艺术美感。',
    '这是一张精美的照片 8。',
    '这是一张精美的照片 9。',
    '这是一张精美的照片 10。',
    '这是一张精美的照片 11。',
    '这是一张精美的照片 12。',
    '这是一张精美的照片 13。',
    '这是一张精美的照片 14。',
    '这是一张精美的照片 15。',
    '这是一张精美的照片 16。',
    '这是一张精美的照片 17。',
    '这是一张精美的照片 18。',
    '这是一张精美的照片 19。',
    '这是一张精美的照片 20。',
    '这是一张精美的照片 21。',
    '这是一张精美的照片 22。',
    '这是一张精美的照片 23。',
    '这是一张精美的照片 24。',
    '这是一张精美的照片 25。',
    '这是一张精美的照片 26。',
    '这是一张精美的照片 27。',
];